spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.191.1:3306/bridge
    username: dqzx
    password: dqzx
#    url: jdbc:mysql://127.0.0.1:3306/demo
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

logging:
  level:
    com:
      example:
        demo:
          dao: debug

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapper/*.xml #  所有的mapper映射文件


pagehelper:                       #pagehelper分页插件
    helperDialect: mysql          #设置数据库方言
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
