-- auto Generated on 2018-08-24 15:32:40 
-- DROP TABLE IF EXISTS `bridge_site_detail`; 
CREATE TABLE bridge_site_detail(
    `bridge_id` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '桥梁ID(联合主键1)',
    `side_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '分幅类型(联合主键2)',
    `site_no` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '孔号(联合主键3)',
    `super_structure_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '上部结构类型',
    `super_structure_type_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'superStructureTypeName',
    `super_material_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '上部结构材料类型',
    `super_force_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '上部结构受力形式',
    `super_construct_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '上部结构施工方式',
    `support_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '支座类型',
    `support_model` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '支座型号',
    `concrete_strength` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '混凝土强度',
    `mid_span_width` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '跨中底板宽',
    `pier_top_width` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '墩顶底板宽',
    `mid_span_height` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '跨中梁高',
    `pier_top_height` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '墩顶梁高',
    `pier_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '桥墩类型',
    `pier_type_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'pierTypeName',
    `pier_force_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '桥墩受力形式',
    `pier_force_type_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'pierForceTypeName',
    `pier_base_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '桥墩基础类型',
    `pier_base_type_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'pierBaseTypeName',
    `pier_base_material_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '桥墩基础材料类型',
    `pier_base_material_type_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'pierBaseMaterialTypeName',
    `pier_base_construct_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '桥墩基础施工方式',
    `pier_base_construct_type_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'pierBaseConstructTypeName',
    `pier_width` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '盖梁宽',
    `pier_thickness` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '盖梁厚',
    `pier_radius` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '墩柱直径',
    `pier_stake_num` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '桥墩桩数',
    `pier_stake_radius` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '桥墩桩径',
    `abutment_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '桥台类型',
    `abutment_force_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '桥台受力形式',
    `abutment_base_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '桥台基础类型',
    `abutment_base_material_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '桥台基础材料类型',
    `abutment_base_construct_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '桥台基础施工方式',
    `abutment_width` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '台宽',
    `abutment_thickness` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '台厚',
    `abutment_radius` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '台柱直径',
    `abutment_stake_num` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '桥台桩数',
    `abutment_stake_radius` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '桥台桩径',
    `super_force_type_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'superForceTypeName',
    `super_construct_type_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'superConstructTypeName',
    `abutment_base_construct_type_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'abutmentBaseConstructTypeName',
    `abutment_base_material_type_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'abutmentBaseMaterialTypeName',
    `abutment_base_type_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'abutmentBaseTypeName',
    `abutment_force_type_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'abutmentForceTypeName',
    `abutment_type_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'abutmentTypeName',
    `underpass_clearance` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'underpassClearance',
    `underpass_purpose_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'underpassPurposeName',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'bridge_site_detail';
